title: 高飞de好文笔记
description: LLM针对好文章的解读笔记
theme: jekyll-theme-minimal

markdown: GFM
collections:
  reads:
    output: true

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
